--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -403,4 +403,6 @@
 obj-$(CONFIG_MSM_FAST_BOOT) += fastboot.o
 obj-$(CONFIG_MSM_FIQ) += msm7k_fiq.o
 obj-$(CONFIG_MSM_FIQ) += msm7k_fiq_handler.o
+
+obj-$(CONFIG_MEMORY_HOLE_CARVEOUT) +=  msm_mem_hole.o
 obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
